import marimo

__generated_with = "0.20.2"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell
def _():
    import duckdb

    # Connect to the DuckDB database generated by your dlt pipeline
    con = duckdb.connect("taxi_pipeline.duckdb")
    return (con,)


@app.cell
def _(con):
    con.execute("SHOW TABLES").fetchall()
    return


@app.cell
def _(con, mo):
    _df = mo.sql(
        f"""
        SELECT MIN(trip_pickup_date_time), MAX(trip_dropoff_date_time) FROM taxi_data.nyc_taxi_data
        """,
        engine=con
    )
    return


@app.cell
def _(con, mo):
    _df = mo.sql(
        f"""
        SELECT COUNT(1) FILTER (WHERE payment_type = 'Credit') / COUNT(1) * 100 AS percent 
        FROM taxi_data.nyc_taxi_data
        """,
        engine=con
    )
    return


@app.cell
def _(con, mo):
    _df = mo.sql(
        f"""
        SELECT ROUND(SUM(tip_amt),2) FROM taxi_data.nyc_taxi_data
        """,
        engine=con
    )
    return


if __name__ == "__main__":
    app.run()
